/* The periodic table, as data.
 *
 * Fourteen numbers and strings per element, laid out one row per element so
 * that a wrong value is a one-line diff rather than a hunt through an object
 * literal. Compiled from PubChem's periodic table dataset; the values are
 * measurements, and where one has never been measured — the electronegativity
 * of neon, the boiling point of oganesson — the entry is NaN rather than a
 * zero that would plot as a real data point at the bottom of the axis.
 *
 * Generated by tools/gen/elements.js and then committed. It is data, not code,
 * and it does not change.
 *
 * Radii are van der Waals in picometres, ionisation energies and electron
 * affinities in electronvolts, temperatures in kelvin, densities in g/cm³.
 */

export type ElementRow = [
  number, // atomic number
  string, // symbol
  string, // name
  number, // relative atomic mass
  number, // van der Waals radius, pm
  number, // electronegativity, Pauling
  number, // first ionisation energy, eV
  number, // electron affinity, eV
  number, // melting point, K
  number, // boiling point, K
  number, // density, g/cm³
  string, // category
  string, // common oxidation states
  string, // year discovered
];

export const ELEMENT_ROWS: ElementRow[] = [
  [1, "H", "Hydrogen", 1.008, 120, 2.2, 13.598, 0.754, 13.81, 20.28, 0.00008988, "Nonmetal", "+1, -1", "1766"],
  [2, "He", "Helium", 4.0026, 140, NaN, 24.587, NaN, 0.95, 4.22, 0.0001785, "Noble gas", "0", "1868"],
  [3, "Li", "Lithium", 7, 182, 0.98, 5.392, 0.618, 453.65, 1615, 0.534, "Alkali metal", "+1", "1817"],
  [4, "Be", "Beryllium", 9.012183, 153, 1.57, 9.323, NaN, 1560, 2744, 1.85, "Alkaline earth metal", "+2", "1798"],
  [5, "B", "Boron", 10.81, 192, 2.04, 8.298, 0.277, 2348, 4273, 2.37, "Metalloid", "+3", "1808"],
  [6, "C", "Carbon", 12.011, 170, 2.55, 11.26, 1.263, 3823, 4098, 2.267, "Nonmetal", "+4, +2, -4", "Ancient"],
  [7, "N", "Nitrogen", 14.007, 155, 3.04, 14.534, NaN, 63.15, 77.36, 0.0012506, "Nonmetal", "+5, +4, +3, +2, +1, -1, -2, -3", "1772"],
  [8, "O", "Oxygen", 15.999, 152, 3.44, 13.618, 1.461, 54.36, 90.2, 0.001429, "Nonmetal", "-2", "1774"],
  [9, "F", "Fluorine", 18.99840316, 135, 3.98, 17.423, 3.339, 53.53, 85.03, 0.001696, "Halogen", "-1", "1670"],
  [10, "Ne", "Neon", 20.18, 154, NaN, 21.565, NaN, 24.56, 27.07, 0.0008999, "Noble gas", "0", "1898"],
  [11, "Na", "Sodium", 22.9897693, 227, 0.93, 5.139, 0.548, 370.95, 1156, 0.97, "Alkali metal", "+1", "1807"],
  [12, "Mg", "Magnesium", 24.305, 173, 1.31, 7.646, NaN, 923, 1363, 1.74, "Alkaline earth metal", "+2", "1808"],
  [13, "Al", "Aluminum", 26.981538, 184, 1.61, 5.986, 0.441, 933.437, 2792, 2.7, "Post-transition metal", "+3", "Ancient"],
  [14, "Si", "Silicon", 28.085, 210, 1.9, 8.152, 1.385, 1687, 3538, 2.3296, "Metalloid", "+4, +2, -4", "1854"],
  [15, "P", "Phosphorus", 30.973762, 180, 2.19, 10.487, 0.746, 317.3, 553.65, 1.82, "Nonmetal", "+5, +3, -3", "1669"],
  [16, "S", "Sulfur", 32.07, 180, 2.58, 10.36, 2.077, 388.36, 717.75, 2.067, "Nonmetal", "+6, +4, -2", "Ancient"],
  [17, "Cl", "Chlorine", 35.45, 175, 3.16, 12.968, 3.617, 171.65, 239.11, 0.003214, "Halogen", "+7, +5, +1, -1", "1774"],
  [18, "Ar", "Argon", 39.9, 188, NaN, 15.76, NaN, 83.8, 87.3, 0.0017837, "Noble gas", "0", "1894"],
  [19, "K", "Potassium", 39.0983, 275, 0.82, 4.341, 0.501, 336.53, 1032, 0.89, "Alkali metal", "+1", "1807"],
  [20, "Ca", "Calcium", 40.08, 231, 1, 6.113, NaN, 1115, 1757, 1.54, "Alkaline earth metal", "+2", "Ancient"],
  [21, "Sc", "Scandium", 44.95591, 211, 1.36, 6.561, 0.188, 1814, 3109, 2.99, "Transition metal", "+3", "1879"],
  [22, "Ti", "Titanium", 47.867, 187, 1.54, 6.828, 0.079, 1941, 3560, 4.5, "Transition metal", "+4, +3, +2", "1791"],
  [23, "V", "Vanadium", 50.9415, 179, 1.63, 6.746, 0.525, 2183, 3680, 6, "Transition metal", "+5, +4, +3, +2", "1801"],
  [24, "Cr", "Chromium", 51.996, 189, 1.66, 6.767, 0.666, 2180, 2944, 7.15, "Transition metal", "+6, +3, +2", "1797"],
  [25, "Mn", "Manganese", 54.93804, 197, 1.55, 7.434, NaN, 1519, 2334, 7.3, "Transition metal", "+7, +4, +3, +2", "1774"],
  [26, "Fe", "Iron", 55.84, 194, 1.83, 7.902, 0.163, 1811, 3134, 7.874, "Transition metal", "+3, +2", "Ancient"],
  [27, "Co", "Cobalt", 58.93319, 192, 1.88, 7.881, 0.661, 1768, 3200, 8.86, "Transition metal", "+3, +2", "1735"],
  [28, "Ni", "Nickel", 58.693, 163, 1.91, 7.64, 1.156, 1728, 3186, 8.912, "Transition metal", "+3, +2", "1751"],
  [29, "Cu", "Copper", 63.55, 140, 1.9, 7.726, 1.228, 1357.77, 2835, 8.933, "Transition metal", "+2, +1", "Ancient"],
  [30, "Zn", "Zinc", 65.4, 139, 1.65, 9.394, NaN, 692.68, 1180, 7.134, "Transition metal", "+2", "1746"],
  [31, "Ga", "Gallium", 69.723, 187, 1.81, 5.999, 0.3, 302.91, 2477, 5.91, "Post-transition metal", "+3", "1875"],
  [32, "Ge", "Germanium", 72.63, 211, 2.01, 7.9, 1.35, 1211.4, 3106, 5.323, "Metalloid", "+4, +2", "1886"],
  [33, "As", "Arsenic", 74.92159, 185, 2.18, 9.815, 0.81, 1090, 887, 5.776, "Metalloid", "+5, +3, -3", "Ancient"],
  [34, "Se", "Selenium", 78.97, 190, 2.55, 9.752, 2.021, 493.65, 958, 4.809, "Nonmetal", "+6, +4, -2", "1817"],
  [35, "Br", "Bromine", 79.9, 183, 2.96, 11.814, 3.365, 265.95, 331.95, 3.11, "Halogen", "+5, +1, -1", "1826"],
  [36, "Kr", "Krypton", 83.8, 202, 3, 14, NaN, 115.79, 119.93, 0.003733, "Noble gas", "0", "1898"],
  [37, "Rb", "Rubidium", 85.468, 303, 0.82, 4.177, 0.468, 312.46, 961, 1.53, "Alkali metal", "+1", "1861"],
  [38, "Sr", "Strontium", 87.62, 249, 0.95, 5.695, NaN, 1050, 1655, 2.64, "Alkaline earth metal", "+2", "1790"],
  [39, "Y", "Yttrium", 88.90584, 219, 1.22, 6.217, 0.307, 1795, 3618, 4.47, "Transition metal", "+3", "1794"],
  [40, "Zr", "Zirconium", 91.22, 186, 1.33, 6.634, 0.426, 2128, 4682, 6.52, "Transition metal", "+4", "1789"],
  [41, "Nb", "Niobium", 92.90637, 207, 1.6, 6.759, 0.893, 2750, 5017, 8.57, "Transition metal", "+5, +3", "1801"],
  [42, "Mo", "Molybdenum", 95.95, 209, 2.16, 7.092, 0.746, 2896, 4912, 10.2, "Transition metal", "+6", "1778"],
  [43, "Tc", "Technetium", 96.90636, 209, 1.9, 7.28, 0.55, 2430, 4538, 11, "Transition metal", "+7, +6, +4", "1937"],
  [44, "Ru", "Ruthenium", 101.1, 207, 2.2, 7.361, 1.05, 2607, 4423, 12.1, "Transition metal", "+3", "1827"],
  [45, "Rh", "Rhodium", 102.9055, 195, 2.28, 7.459, 1.137, 2237, 3968, 12.4, "Transition metal", "+3", "1803"],
  [46, "Pd", "Palladium", 106.42, 202, 2.2, 8.337, 0.557, 1828.05, 3236, 12, "Transition metal", "+3, +2", "1803"],
  [47, "Ag", "Silver", 107.868, 172, 1.93, 7.576, 1.302, 1234.93, 2435, 10.501, "Transition metal", "+1", "Ancient"],
  [48, "Cd", "Cadmium", 112.41, 158, 1.69, 8.994, NaN, 594.22, 1040, 8.69, "Transition metal", "+2", "1817"],
  [49, "In", "Indium", 114.818, 193, 1.78, 5.786, 0.3, 429.75, 2345, 7.31, "Post-transition metal", "+3", "1863"],
  [50, "Sn", "Tin", 118.71, 217, 1.96, 7.344, 1.2, 505.08, 2875, 7.287, "Post-transition metal", "+4, +2", "Ancient"],
  [51, "Sb", "Antimony", 121.76, 206, 2.05, 8.64, 1.07, 903.78, 1860, 6.685, "Metalloid", "+5, +3, -3", "Ancient"],
  [52, "Te", "Tellurium", 127.6, 206, 2.1, 9.01, 1.971, 722.66, 1261, 6.232, "Metalloid", "+6, +4, -2", "1782"],
  [53, "I", "Iodine", 126.9045, 198, 2.66, 10.451, 3.059, 386.85, 457.55, 4.93, "Halogen", "+7, +5, +1, -1", "1811"],
  [54, "Xe", "Xenon", 131.29, 216, 2.6, 12.13, NaN, 161.36, 165.03, 0.005887, "Noble gas", "0", "1898"],
  [55, "Cs", "Cesium", 132.905452, 343, 0.79, 3.894, 0.472, 301.59, 944, 1.93, "Alkali metal", "+1", "1860"],
  [56, "Ba", "Barium", 137.33, 268, 0.89, 5.212, NaN, 1000, 2170, 3.62, "Alkaline earth metal", "+2", "1808"],
  [57, "La", "Lanthanum", 138.9055, 240, 1.1, 5.577, 0.5, 1191, 3737, 6.15, "Lanthanide", "+3", "1839"],
  [58, "Ce", "Cerium", 140.116, 235, 1.12, 5.539, 0.5, 1071, 3697, 6.77, "Lanthanide", "+4, +3", "1803"],
  [59, "Pr", "Praseodymium", 140.90766, 239, 1.13, 5.464, NaN, 1204, 3793, 6.77, "Lanthanide", "+3", "1885"],
  [60, "Nd", "Neodymium", 144.24, 229, 1.14, 5.525, NaN, 1294, 3347, 7.01, "Lanthanide", "+3", "1885"],
  [61, "Pm", "Promethium", 144.91276, 236, NaN, 5.55, NaN, 1315, 3273, 7.26, "Lanthanide", "+3", "1945"],
  [62, "Sm", "Samarium", 150.4, 229, 1.17, 5.644, NaN, 1347, 2067, 7.52, "Lanthanide", "+3, +2", "1879"],
  [63, "Eu", "Europium", 151.964, 233, NaN, 5.67, NaN, 1095, 1802, 5.24, "Lanthanide", "+3, +2", "1901"],
  [64, "Gd", "Gadolinium", 157.2, 237, 1.2, 6.15, NaN, 1586, 3546, 7.9, "Lanthanide", "+3", "1880"],
  [65, "Tb", "Terbium", 158.92535, 221, NaN, 5.864, NaN, 1629, 3503, 8.23, "Lanthanide", "+3", "1843"],
  [66, "Dy", "Dysprosium", 162.5, 229, 1.22, 5.939, NaN, 1685, 2840, 8.55, "Lanthanide", "+3", "1886"],
  [67, "Ho", "Holmium", 164.93033, 216, 1.23, 6.022, NaN, 1747, 2973, 8.8, "Lanthanide", "+3", "1878"],
  [68, "Er", "Erbium", 167.26, 235, 1.24, 6.108, NaN, 1802, 3141, 9.07, "Lanthanide", "+3", "1843"],
  [69, "Tm", "Thulium", 168.93422, 227, 1.25, 6.184, NaN, 1818, 2223, 9.32, "Lanthanide", "+3", "1879"],
  [70, "Yb", "Ytterbium", 173.05, 242, NaN, 6.254, NaN, 1092, 1469, 6.9, "Lanthanide", "+3, +2", "1878"],
  [71, "Lu", "Lutetium", 174.9668, 221, 1.27, 5.426, NaN, 1936, 3675, 9.84, "Lanthanide", "+3", "1907"],
  [72, "Hf", "Hafnium", 178.49, 212, 1.3, 6.825, NaN, 2506, 4876, 13.3, "Transition metal", "+4", "1923"],
  [73, "Ta", "Tantalum", 180.9479, 217, 1.5, 7.89, 0.322, 3290, 5731, 16.4, "Transition metal", "+5", "1802"],
  [74, "W", "Tungsten", 183.84, 210, 2.36, 7.98, 0.815, 3695, 5828, 19.3, "Transition metal", "+6", "1783"],
  [75, "Re", "Rhenium", 186.207, 217, 1.9, 7.88, 0.15, 3459, 5869, 20.8, "Transition metal", "+7, +6, +4", "1925"],
  [76, "Os", "Osmium", 190.2, 216, 2.2, 8.7, 1.1, 3306, 5285, 22.57, "Transition metal", "+4, +3", "1803"],
  [77, "Ir", "Iridium", 192.22, 202, 2.2, 9.1, 1.565, 2719, 4701, 22.42, "Transition metal", "+4, +3", "1803"],
  [78, "Pt", "Platinum", 195.08, 209, 2.28, 9, 2.128, 2041.55, 4098, 21.46, "Transition metal", "+4, +2", "1735"],
  [79, "Au", "Gold", 196.96657, 166, 2.54, 9.226, 2.309, 1337.33, 3129, 19.282, "Transition metal", "+3, +1", "Ancient"],
  [80, "Hg", "Mercury", 200.59, 209, 2, 10.438, NaN, 234.32, 629.88, 13.5336, "Transition metal", "+2, +1", "Ancient"],
  [81, "Tl", "Thallium", 204.383, 196, 1.62, 6.108, 0.2, 577, 1746, 11.8, "Post-transition metal", "+3, +1", "1861"],
  [82, "Pb", "Lead", 207, 202, 2.33, 7.417, 0.36, 600.61, 2022, 11.342, "Post-transition metal", "+4, +2", "Ancient"],
  [83, "Bi", "Bismuth", 208.9804, 207, 2.02, 7.289, 0.946, 544.55, 1837, 9.807, "Post-transition metal", "+5, +3", "1753"],
  [84, "Po", "Polonium", 208.98243, 197, 2, 8.417, 1.9, 527, 1235, 9.32, "Metalloid", "+4, +2", "1898"],
  [85, "At", "Astatine", 209.98715, 202, 2.2, 9.5, 2.8, 575, NaN, 7, "Halogen", "7, 5, 3, 1, -1", "1940"],
  [86, "Rn", "Radon", 222.01758, 220, NaN, 10.745, NaN, 202, 211.45, 0.00973, "Noble gas", "0", "1900"],
  [87, "Fr", "Francium", 223.01973, 348, 0.7, 3.9, 0.47, 300, NaN, NaN, "Alkali metal", "+1", "1939"],
  [88, "Ra", "Radium", 226.02541, 283, 0.9, 5.279, NaN, 973, 1413, 5, "Alkaline earth metal", "+2", "1898"],
  [89, "Ac", "Actinium", 227.02775, 260, 1.1, 5.17, NaN, 1324, 3471, 10.07, "Actinide", "+3", "1899"],
  [90, "Th", "Thorium", 232.038, 237, 1.3, 6.08, NaN, 2023, 5061, 11.72, "Actinide", "+4", "1828"],
  [91, "Pa", "Protactinium", 231.03588, 243, 1.5, 5.89, NaN, 1845, NaN, 15.37, "Actinide", "+5, +4", "1913"],
  [92, "U", "Uranium", 238.0289, 240, 1.38, 6.194, NaN, 1408, 4404, 18.95, "Actinide", "+6, +5, +4, +3", "1789"],
  [93, "Np", "Neptunium", 237.048172, 221, 1.36, 6.266, NaN, 917, 4175, 20.25, "Actinide", "+6, +5, +4, +3", "1940"],
  [94, "Pu", "Plutonium", 244.0642, 243, 1.28, 6.06, NaN, 913, 3501, 19.84, "Actinide", "+6, +5, +4, +3", "1940"],
  [95, "Am", "Americium", 243.06138, 244, 1.3, 5.993, NaN, 1449, 2284, 13.69, "Actinide", "+6, +5, +4, +3", "1944"],
  [96, "Cm", "Curium", 247.07035, 245, 1.3, 6.02, NaN, 1618, 3400, 13.51, "Actinide", "+3", "1944"],
  [97, "Bk", "Berkelium", 247.07031, 244, 1.3, 6.23, NaN, 1323, NaN, 14, "Actinide", "+4, +3", "1949"],
  [98, "Cf", "Californium", 251.07959, 245, 1.3, 6.3, NaN, 1173, NaN, NaN, "Actinide", "+3", "1950"],
  [99, "Es", "Einsteinium", 252.083, 245, 1.3, 6.42, NaN, 1133, NaN, NaN, "Actinide", "+3", "1952"],
  [100, "Fm", "Fermium", 257.09511, NaN, 1.3, 6.5, NaN, 1800, NaN, NaN, "Actinide", "+3", "1952"],
  [101, "Md", "Mendelevium", 258.09843, NaN, 1.3, 6.58, NaN, 1100, NaN, NaN, "Actinide", "+3, +2", "1955"],
  [102, "No", "Nobelium", 259.101, NaN, 1.3, 6.65, NaN, 1100, NaN, NaN, "Actinide", "+3, +2", "1957"],
  [103, "Lr", "Lawrencium", 266.12, NaN, 1.3, NaN, NaN, 1900, NaN, NaN, "Actinide", "+3", "1961"],
  [104, "Rf", "Rutherfordium", 267.122, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Transition metal", "+4", "1964"],
  [105, "Db", "Dubnium", 268.126, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Transition metal", "5, 4, 3", "1967"],
  [106, "Sg", "Seaborgium", 269.128, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Transition metal", "6, 5, 4, 3, 0", "1974"],
  [107, "Bh", "Bohrium", 270.133, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Transition metal", "7, 5, 4, 3", "1976"],
  [108, "Hs", "Hassium", 269.1336, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Transition metal", "8, 6, 5, 4, 3, 2", "1984"],
  [109, "Mt", "Meitnerium", 277.154, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Transition metal", "9, 8, 6, 4, 3, 1", "1982"],
  [110, "Ds", "Darmstadtium", 282.166, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Transition metal", "8, 6, 4, 2, 0", "1994"],
  [111, "Rg", "Roentgenium", 282.169, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Transition metal", "5, 3, 1, -1", "1994"],
  [112, "Cn", "Copernicium", 286.179, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Transition metal", "2, 1, 0", "1996"],
  [113, "Nh", "Nihonium", 286.182, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Post-transition metal", "", "2004"],
  [114, "Fl", "Flerovium", 290.192, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Post-transition metal", "6, 4,2, 1, 0", "1998"],
  [115, "Mc", "Moscovium", 290.196, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Post-transition metal", "3, 1", "2003"],
  [116, "Lv", "Livermorium", 293.205, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Post-transition metal", "+4, +2, -2", "2000"],
  [117, "Ts", "Tennessine", 294.211, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Halogen", "+5, +3, +1, -1", "2010"],
  [118, "Og", "Oganesson", 295.216, NaN, NaN, NaN, NaN, NaN, NaN, NaN, "Noble gas", "+6, +4, +2, +1, 0, -1", "2006"],
];
